title: "YrGrib"               # Page title
description: "Get the best weather data for your sailing trip in Norway in the best GRIB viewer app."     # Subtitle/tagline
github:
  repository_url: false              # Hide repo URL link
  repository_name: false             # Hide repo name
  is_project_page: false              # Prevent GitHub project page link
theme: jekyll-theme-minimal          # or your theme choice
